- name: template
  template:
    src: pipeline.xml
    dest: /tmp/pipeline.xml
  loop:
    - { repoName: "cart", componentName: "cart" }
- name: Create a jenkins job using the token
  community.general.jenkins_job:
    config: "{{ lookup('file', 'tmp/pipeline.xml') }}"
    name: "test"
    url: "http://172.31.5.238:8080"
    user: "admin"
    token: "11eb1cacb10b766d40cfc6e49a3c759eb6"

