#- name: Create a jenkins job using the token
#  community.general.jenkins_job:
#    config: "{{ lookup('template', 'templates/pipeline.xml') }}"
#    name: test
#    url: http://172.31.5.238:8080
#    user: admin
#    password: admin123
#  loop:
#    - {repoName: "cart", componentName:" "cart"}

- name: tesat
  community.general.jenkins_job_info:
    name: simple
    user: venkatesh
    password: 950235
    url: http://172.31.5.238:8080
